"""Add accessibility_settings_configured field to User model

Revision ID: 713a2731ab3f
Revises: 397a19e7865d
Create Date: 2025-02-18 16:36:12.530725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '713a2731ab3f'
down_revision = '397a19e7865d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accessibility_settings_configured', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('accessibility_settings_configured')

    # ### end Alembic commands ###
